main: com.cavetale.wardrobe.WardrobePlugin

name: Wardrobe
version: 0.1
description: Wardrobe Plugin
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/Wardrobe

depend: [Core, Mytems, SQL, Inventory, PlayerCache, Title]
softdepend: []

commands:

  wardrobe:
    aliases: []
    description: Wardrobe Command
    permission: wardrobe.wardrobe
    usage: |-
      /wardrobe

  wardrobeadmin:
    aliases: [wardrobeadm]
    description: Admin Interface
    permission: wardrobe.admin
    usage: /wardrobeadm

permissions:

  wardrobe.wardrobe:
    description: Use /wardrobe
    default: op

  wardrobe.admin:
    description: Wardrobe admin
    default: op

  wardrobe.ad:
    description: Receive an ad
    default: false

  wardrobe.all:
    description: Unlock all skins
    default: false